services:
  - type: web
    name: nail-studio-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node index.js
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        scope: build,runtime
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
        scope: build,runtime
